### ISSUE TITLE
Support for PHP 8.4

### ISSUE THREAD

**Issue by ramosmd** [rfay/ddev-php-patch-build#4]
Hey folks,

Do you intend to add support for PHP 8.4 soon? It would be nice to have it. ;) 

Thanks for creating this add-on, btw!

Cheers!

**Comment by rfay** [comment]
Hi @ramosmd - It already supports whatever the upstream supports, so should already work fine. I opened 
* https://github.com/rfay/ddev-php-patch-build/pull/5
